### ISSUE TITLE
gulp dev crashes and creates empty minified js files

### ISSUE THREAD

**Issue by johnpitchko** [StartBootstrap/startbootstrap-agency#61]
```
vagrant@scotchbox:/var/www/public$ gulp dev
[03:25:05] Using gulpfile /var/www/public/gulpfile.js
[03:25:05] Starting 'browserSync'...
[03:25:05] Finished 'browserSync' after 65 ms
[03:25:05] Starting 'less'...
[03:25:05] Starting 'minify-css'...
[03:25:05] Starting 'minify-js'...
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.2.15:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 ----------------------------------
[BS] Serving files from: ./
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:860:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:339:9)
    at module.exports (/var/www/public/node_modules/opn/index.js:79:24)
    at Object.utils.open (/var/www/public/node_modules/browser-sync/lib/utils.js:174:23)
    at Object.utils.openBrowser (/var/www/public/node_modules/browser-sync/lib/utils.js:164:23)
    at EventEmitter.events.service:running (/var/www/public/node_modules/browser-sync/lib/internal-events.js:45:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at /var/www/public/node_modules/browser-sync/lib/browser-sync.js:260:19
```

**Comment by davidtmiller** [comment]
Hmm, I am not sure on this one. It seems to be working on my end...I am not a Gulp guru so I am not sure how to troubleshoot this one unfortunately...

**Comment by davidtmiller** [comment]
Just tested this and it should be working. Make sure you're running `npm install` again possibly? Not sure on this but everything seems to be working with the newly renamed `gulp watch` task.
